import type { Metadata } from "next";
import Link from "next/link"
import Image from "next/image"
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/ui/theme-changer"
import {
  NavigationMenu,
  // NavigationMenuContent,
  // NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  // NavigationMenuTrigger,
  // NavigationMenuViewport,
} from "@/components/ui/navigation-menu"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="bg-white dark:bg-teal-500"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <div className="fixed inset-0 pointer-events-none -z-20" >
            <div className="h-full w-full" style={{ background: 'linear-gradient(180deg, rgba(255,255,255,0.0) 0%, rgba(3,4,94,0.8) 100%)' }} />
            {/* <div className="h-full w-full" style={{ background: 'linear-gradient(180deg, rgba(255,255,255,0.0) 0%, rgba(131,201,244,1) 100%)' }} /> */}
          </div >
          <div className="sticky top-0 flex justify-center items-center z-10 dark:bg-gray-900/10 bg-[rgba(219,233,238,1)] backdrop-blur-xl border-b border-b-white">
            <Image src="/swim-icon.svg" alt="swimming" width={30} height={0} className="absolute top-1.5 left-2" />
            <p className="absolute top-2 left-11 text-xl" >MEETS LIVE</p>
            <NavigationMenu>
              <NavigationMenuList className="flex-wrap">
                <NavigationMenuItem>
                  <NavigationMenuLink asChild className="text-xl hover:bg-white/10 focus:bg-white/10">
                    <Link href="/">Home</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink asChild className="text-xl hover:bg-white/10 focus:bg-white/10">
                    <Link href="/meets">Meets</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink asChild className="text-xl hover:bg-white/10 focus:bg-white/10">
                    <Link href="/teams">Teams</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink asChild className="text-xl hover:bg-white/10 focus:bg-white/10">
                    <Link href="swimmers">Swimmers</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
            <ThemeToggle />
          </div>
        </ThemeProvider>
        {children}
      </body>
    </html>
  );
}
